#!/bin/bash

# Create an encrypted secret in ~/.secrets/

bash -cv "gpg --cipher-algo AES256 --output ~/.secrets/$1.gpg --symmetric $1" && \
	chmod -v 400 ~/.secrets/$1.gpg && \
	echo "" && \
	echo "Remember to run:" && \
	echo "shred -z $1"
